import { Request, Response } from 'express';
import UAParser from 'ua-parser-js';
import prisma from '../config/db.js';

/**
 * Tracks a client analytics packet.
 * Updates an existing session by ID or creates a new one.
 */
export const trackSession = async (req: Request, res: Response) => {
  const {
    sessionId, // generated by client (acts as primary key)
    flipbookId,
    visitorId,
    duration,
    pagesRead,
    downloaded,
    shared,
    sharePlatform,
    embedded,
    referrer
  } = req.body;

  if (!sessionId || !flipbookId || !visitorId) {
    return res.status(400).json({ error: 'Session ID, Flipbook ID, and Visitor ID are required' });
  }

  try {
    // 1. Get User-Agent details
    const uaHeader = req.headers['user-agent'] || '';
    const parser = new UAParser(uaHeader);
    const uaResult = parser.getResult();

    const device = uaResult.device.type || 'desktop'; // desktop, mobile, tablet
    const browser = uaResult.browser.name || 'unknown';
    const os = uaResult.os.name || 'unknown';

    // 2. Resolve IP Geolocation
    // Check common proxy headers first, then request ip
    const ip = (req.headers['x-forwarded-for'] as string) || req.socket.remoteAddress || '';
    let country = 'United States'; // Fallback for local dev
    let city = 'Local Network';

    // In a production server, we can query geoip-lite or a free API.
    // For local loopbacks, we keep standard dev mock.
    if (ip && !ip.includes('127.0.0.1') && !ip.includes('::1') && ip.includes('.')) {
      // Production code can do lookup, e.g., using a lightweight check
      // For this build, we mock dynamic values based on IP segments to show realistic data in demo
      const segments = ip.split('.');
      const num = parseInt(segments[0], 10);
      if (num < 50) {
        country = 'United Kingdom';
        city = 'London';
      } else if (num < 100) {
        country = 'Germany';
        city = 'Berlin';
      } else if (num < 150) {
        country = 'India';
        city = 'Mumbai';
      } else if (num < 200) {
        country = 'Canada';
        city = 'Toronto';
      }
    }

    // 3. Upsert Analytics Session in DB to prevent duplicates
    const finalReferrer = referrer || req.headers.referer || 'direct';

    const analytics = await prisma.analytics.upsert({
      where: { id: sessionId },
      update: {
        duration: duration !== undefined ? duration : 0,
        pagesRead: pagesRead !== undefined ? pagesRead : [],
        downloaded: downloaded || false,
        shared: shared || false,
        sharePlatform: sharePlatform || null,
      },
      create: {
        id: sessionId,
        flipbookId,
        visitorId,
        country,
        city,
        device,
        browser,
        os,
        referrer: finalReferrer,
        duration: duration !== undefined ? duration : 0,
        pagesRead: pagesRead !== undefined ? pagesRead : [],
        downloaded: downloaded || false,
        shared: shared || false,
        sharePlatform: sharePlatform || null,
        embedded: embedded || false,
      },
    });

    return res.status(200).json({ status: 'success', sessionId: analytics.id });
  } catch (err) {
    console.error('[AnalyticsController] Tracking error:', err);
    return res.status(500).json({ error: 'Failed to record tracking packet' });
  }
};

/**
 * Generates an aggregated analytics report for a specific flipbook.
 */
export const getFlipbookReport = async (req: Request, res: Response) => {
  const { id } = req.params;

  try {
    // Verify flipbook exists
    const flipbook = await prisma.flipbook.findUnique({
      where: { id },
    });

    if (!flipbook) {
      return res.status(404).json({ error: 'Flipbook not found' });
    }

    const sessions = await prisma.analytics.findMany({
      where: { flipbookId: id },
      orderBy: { createdAt: 'asc' },
    });

    // 1. Core Summary metrics
    const totalViews = sessions.length;
    const uniqueVisitors = new Set(sessions.map((s) => s.visitorId)).size;
    
    let totalDuration = 0;
    let completedSessionsCount = 0; // Read last page
    
    const deviceCounts: Record<string, number> = { desktop: 0, mobile: 0, tablet: 0 };
    const countryCounts: Record<string, number> = {};
    const osCounts: Record<string, number> = {};
    const referrerCounts: Record<string, number> = {};

    // Group views by date for the timeline chart
    const timelineDataMap: Record<string, number> = {};

    sessions.forEach((s) => {
      totalDuration += s.duration;

      // Completion Rate: if pagesRead contains the last page of the flipbook
      if (flipbook.pageCount > 0 && s.pagesRead.includes(flipbook.pageCount)) {
        completedSessionsCount++;
      }

      // Device aggregation
      const devType = s.device?.toLowerCase() || 'desktop';
      if (deviceCounts[devType] !== undefined) {
        deviceCounts[devType]++;
      } else {
        deviceCounts.desktop++;
      }

      // Country aggregation
      const countryName = s.country || 'Unknown';
      countryCounts[countryName] = (countryCounts[countryName] || 0) + 1;

      // OS aggregation
      const osName = s.os || 'Unknown';
      osCounts[osName] = (osCounts[osName] || 0) + 1;

      // Referrer aggregation
      let ref = 'Direct / Email';
      if (s.referrer && s.referrer !== 'direct') {
        try {
          const url = new URL(s.referrer);
          ref = url.hostname;
        } catch {
          ref = s.referrer;
        }
      }
      referrerCounts[ref] = (referrerCounts[ref] || 0) + 1;

      // Timeline aggregation (YYYY-MM-DD)
      const dateStr = s.createdAt.toISOString().split('T')[0];
      timelineDataMap[dateStr] = (timelineDataMap[dateStr] || 0) + 1;
    });

    const averageReadingTime = totalViews > 0 ? Math.round(totalDuration / totalViews) : 0;
    const completionRate = totalViews > 0 ? Math.round((completedSessionsCount / totalViews) * 100) : 0;

    // Convert objects to sorted arrays for charting
    const formatAggregate = (counts: Record<string, number>) => {
      return Object.entries(counts)
        .map(([name, value]) => ({ name, value }))
        .sort((a, b) => b.value - a.value)
        .slice(0, 5); // top 5
    };

    const countries = formatAggregate(countryCounts);
    const devices = Object.entries(deviceCounts).map(([name, value]) => ({ name, value }));
    const os = formatAggregate(osCounts);
    const referrers = formatAggregate(referrerCounts);

    // Generate timeline (last 7 days by default or available data)
    const timeline = Object.entries(timelineDataMap).map(([date, views]) => ({
      date,
      views
    }));

    return res.status(200).json({
      report: {
        totalViews,
        uniqueVisitors,
        averageReadingTime, // in seconds
        completionRate, // %
        countries,
        devices,
        os,
        referrers,
        timeline
      }
    });
  } catch (err) {
    console.error('[AnalyticsController] Fetch report error:', err);
    return res.status(500).json({ error: 'Failed to generate analytics report' });
  }
};
